/*
The implied super() call in Bottom2’s constructor cannot be satisfied because
there isn’t a no-arg constructor in Top. A default, no-arg constructor is generated by the
compiler only if the class has no constructor defined explicitly.
 */

package com.overloadoverride;

class Top {
    Top(){}                 //This no-argu constructor is important as it is required by Bottom2 when 
    						//it invoke super(),try commenting this line
    public Top(String s) { System.out.print("B"); }

}
public class Bottom2 extends Top {
public Bottom2(String s) {
	super(s);
    System.out.print("D"); }

public static void main(String [] args) {
    new Bottom2("C");
    System.out.println(" ");
}

}